server:
  port: 8888
  #port: 9002

mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.zb.base.mapper     # 所有Entity别名类所在包
  mapper-locations:
    - classpath:com/zb/base/mapper/*.xml
  #classpath:/com/zb/spider9002/dao/*.xml                     # mapper映射文件

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://47.106.75.184:3306/myRaPost              # 数据库名称
    username: root
    password: 19971216zb
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 2000000                                  # 等待连接获取的最大超时时间

logging:
  level:
    com:
      zb:
        spider9002:
          mapper: debug
  file: log
  path: ./log